name: CI

on:
  push:
    branches: [main]
    paths-ignore:
      - '.github/ISSUE_TEMPLATE/**'
      - '**/README.md'
  workflow_dispatch:

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    if: ${{ github.event_name != 'push' || !startsWith(github.event.head_commit.message, '[skip ci]') }}
    strategy:
      matrix:
        arch: [universal, arm, arm64, x86, x86_64]
      fail-fast: false
    uses: ./.github/workflows/build.yml
    with:
      arch: ${{ matrix.arch }}
      build_debug: true
      build_release: true
    secrets:
      KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
      KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}

